name: Trigger auto deployment for ca-external-dev-eastus2-001

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'docker/images/n8n/**'
    - '.github/workflows/ca-external-dev-eastus2-001-AutoDeployTrigger-a0ef5184-7541-4189-bd78-b4686e42dc80.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CAEXTERNALDEVEASTUS2001_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/docker/images/n8n 
          registryUrl: acrstartseprodeastus2001.azurecr.io
          registryUsername: ${{ secrets.CAEXTERNALDEVEASTUS2001_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CAEXTERNALDEVEASTUS2001_REGISTRY_PASSWORD }}
          containerAppName: ca-external-dev-eastus2-001
          resourceGroup: rg-startse-prod-eastus2
          imageToBuild: acrstartseprodeastus2001.azurecr.io/ca-external-dev-eastus2-001:${{ github.sha }}
          
            

     

